all: \
  Output/Release/Exe/Dongle_Test_3.elf\

-include Output/Release/Obj/Dongle_Test_3/system_nrf52.d
Output/Release/Obj/Dongle_Test_3/system_nrf52.o:nRF/Device/Source/system_nrf52.c
	C:/Users/shsingha/ncs/v1.8.0/toolchain/segger_embedded_studio/gcc/arm-none-eabi/bin/cc1 -fmessage-length=0 -fno-diagnostics-show-caret -std=gnu99 -mcpu=cortex-m4 -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -mtp=soft -mfp16-format=ieee -munaligned-access -nostdinc -isystemC:/Users/shsingha/ncs/v1.8.0/toolchain/segger_embedded_studio/include -IC:/Users/shsingha/WorkSpace/SES/Dongle_Test_3/nRF/Device/Include "-IC:/Users/shsingha/Nordic/SEGGER Embedded Studio/v3/packages/CMSIS_5/CMSIS/Core/Include" -D__SIZEOF_WCHAR_T=4 -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=8192 -D__SES_VERSION=56800 -D__GNU_LINKER -DNDEBUG -DARM_MATH_CM4 -DNRF52840_XXAA -D__nRF_FAMILY -DFLASH_PLACEMENT=1 -MD C:/Users/shsingha/WorkSpace/SES/Dongle_Test_3/Output/Release/Obj/Dongle_Test_3/system_nrf52.d -MQ Output/Release/Obj/Dongle_Test_3/system_nrf52.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -fno-dwarf2-cfi-asm -ffunction-sections -fdata-sections -mtext=.init -mrodata=.init_rodata -fshort-enums -fno-common C:\Users\shsingha\WorkSpace\SES\Dongle_Test_3\nRF\Device\Source\system_nrf52.c -o C:/Users/shsingha/WorkSpace/SES/Dongle_Test_3/Output/Release/Obj/Dongle_Test_3/system_nrf52.asm
	C:/Users/shsingha/ncs/v1.8.0/toolchain/segger_embedded_studio/gcc/arm-none-eabi/bin/as --traditional-format -IC:/Users/shsingha/WorkSpace/SES/Dongle_Test_3/nRF/Device/Include -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb C:/Users/shsingha/WorkSpace/SES/Dongle_Test_3/Output/Release/Obj/Dongle_Test_3/system_nrf52.asm -o Output/Release/Obj/Dongle_Test_3/system_nrf52.o
	C:/Users/shsingha/ncs/v1.8.0/toolchain/segger_embedded_studio/bin/rm C:/Users/shsingha/WorkSpace/SES/Dongle_Test_3/Output/Release/Obj/Dongle_Test_3/system_nrf52.asm

-include Output/Release/Obj/Dongle_Test_3/main.d
Output/Release/Obj/Dongle_Test_3/main.o:main.c
	C:/Users/shsingha/ncs/v1.8.0/toolchain/segger_embedded_studio/gcc/arm-none-eabi/bin/cc1 -fmessage-length=0 -fno-diagnostics-show-caret -std=gnu99 -mcpu=cortex-m4 -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -mtp=soft -mfp16-format=ieee -munaligned-access -nostdinc -isystemC:/Users/shsingha/ncs/v1.8.0/toolchain/segger_embedded_studio/include -IC:/Users/shsingha/WorkSpace/SES/Dongle_Test_3/nRF/Device/Include "-IC:/Users/shsingha/Nordic/SEGGER Embedded Studio/v3/packages/CMSIS_5/CMSIS/Core/Include" -D__SIZEOF_WCHAR_T=4 -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=8192 -D__SES_VERSION=56800 -D__GNU_LINKER -DNDEBUG -DARM_MATH_CM4 -DNRF52840_XXAA -D__nRF_FAMILY -DFLASH_PLACEMENT=1 -MD C:/Users/shsingha/WorkSpace/SES/Dongle_Test_3/Output/Release/Obj/Dongle_Test_3/main.d -MQ Output/Release/Obj/Dongle_Test_3/main.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -fno-dwarf2-cfi-asm -ffunction-sections -fdata-sections -fshort-enums -fno-common C:\Users\shsingha\WorkSpace\SES\Dongle_Test_3\main.c -o C:/Users/shsingha/WorkSpace/SES/Dongle_Test_3/Output/Release/Obj/Dongle_Test_3/main.asm
	C:/Users/shsingha/ncs/v1.8.0/toolchain/segger_embedded_studio/gcc/arm-none-eabi/bin/as --traditional-format -IC:/Users/shsingha/WorkSpace/SES/Dongle_Test_3/nRF/Device/Include -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb C:/Users/shsingha/WorkSpace/SES/Dongle_Test_3/Output/Release/Obj/Dongle_Test_3/main.asm -o Output/Release/Obj/Dongle_Test_3/main.o
	C:/Users/shsingha/ncs/v1.8.0/toolchain/segger_embedded_studio/bin/rm C:/Users/shsingha/WorkSpace/SES/Dongle_Test_3/Output/Release/Obj/Dongle_Test_3/main.asm

-include Output/Release/Obj/Dongle_Test_3/ses_startup_nrf_common.d
Output/Release/Obj/Dongle_Test_3/ses_startup_nrf_common.o:nRF/Device/Startup/ses_startup_nrf_common.s
	C:/Users/shsingha/ncs/v1.8.0/toolchain/segger_embedded_studio/gcc/arm-none-eabi/bin/cc1 -fmessage-length=0 -fno-diagnostics-show-caret -std=gnu99 -E -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -nostdinc -isystemC:/Users/shsingha/ncs/v1.8.0/toolchain/segger_embedded_studio/include -IC:/Users/shsingha/WorkSpace/SES/Dongle_Test_3/nRF/Device/Include "-IC:/Users/shsingha/Nordic/SEGGER Embedded Studio/v3/packages/CMSIS_5/CMSIS/Core/Include" -D__SIZEOF_WCHAR_T=4 -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=8192 -D__SES_VERSION=56800 -D__GNU_LINKER -DNDEBUG -DARM_MATH_CM4 -DNRF52840_XXAA -D__nRF_FAMILY -DFLASH_PLACEMENT=1 -MD C:/Users/shsingha/WorkSpace/SES/Dongle_Test_3/Output/Release/Obj/Dongle_Test_3/ses_startup_nrf_common.d -MQ Output/Release/Obj/Dongle_Test_3/ses_startup_nrf_common.o -quiet -lang-asm C:\Users\shsingha\WorkSpace\SES\Dongle_Test_3\nRF\Device\Startup\ses_startup_nrf_common.s -o C:/Users/shsingha/WorkSpace/SES/Dongle_Test_3/Output/Release/Obj/Dongle_Test_3/ses_startup_nrf_common_PP.s
	C:/Users/shsingha/ncs/v1.8.0/toolchain/segger_embedded_studio/gcc/arm-none-eabi/bin/as --traditional-format -IC:/Users/shsingha/WorkSpace/SES/Dongle_Test_3/nRF/Device/Include -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb C:/Users/shsingha/WorkSpace/SES/Dongle_Test_3/Output/Release/Obj/Dongle_Test_3/ses_startup_nrf_common_PP.s -o Output/Release/Obj/Dongle_Test_3/ses_startup_nrf_common.o -g -gdwarf-4
	C:/Users/shsingha/ncs/v1.8.0/toolchain/segger_embedded_studio/bin/rm C:/Users/shsingha/WorkSpace/SES/Dongle_Test_3/Output/Release/Obj/Dongle_Test_3/ses_startup_nrf_common_PP.s

-include Output/Release/Obj/Dongle_Test_3/ses_startup_nrf52840.d
Output/Release/Obj/Dongle_Test_3/ses_startup_nrf52840.o:nRF/Device/Startup/ses_startup_nrf52840.s
	C:/Users/shsingha/ncs/v1.8.0/toolchain/segger_embedded_studio/gcc/arm-none-eabi/bin/cc1 -fmessage-length=0 -fno-diagnostics-show-caret -std=gnu99 -E -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -nostdinc -isystemC:/Users/shsingha/ncs/v1.8.0/toolchain/segger_embedded_studio/include -IC:/Users/shsingha/WorkSpace/SES/Dongle_Test_3/nRF/Device/Include "-IC:/Users/shsingha/Nordic/SEGGER Embedded Studio/v3/packages/CMSIS_5/CMSIS/Core/Include" -D__SIZEOF_WCHAR_T=4 -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=8192 -D__SES_VERSION=56800 -D__GNU_LINKER -DNDEBUG -DARM_MATH_CM4 -DNRF52840_XXAA -D__nRF_FAMILY -DFLASH_PLACEMENT=1 -MD C:/Users/shsingha/WorkSpace/SES/Dongle_Test_3/Output/Release/Obj/Dongle_Test_3/ses_startup_nrf52840.d -MQ Output/Release/Obj/Dongle_Test_3/ses_startup_nrf52840.o -quiet -lang-asm C:\Users\shsingha\WorkSpace\SES\Dongle_Test_3\nRF\Device\Startup\ses_startup_nrf52840.s -o C:/Users/shsingha/WorkSpace/SES/Dongle_Test_3/Output/Release/Obj/Dongle_Test_3/ses_startup_nrf52840_PP.s
	C:/Users/shsingha/ncs/v1.8.0/toolchain/segger_embedded_studio/gcc/arm-none-eabi/bin/as --traditional-format -IC:/Users/shsingha/WorkSpace/SES/Dongle_Test_3/nRF/Device/Include -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb C:/Users/shsingha/WorkSpace/SES/Dongle_Test_3/Output/Release/Obj/Dongle_Test_3/ses_startup_nrf52840_PP.s -o Output/Release/Obj/Dongle_Test_3/ses_startup_nrf52840.o -g -gdwarf-4
	C:/Users/shsingha/ncs/v1.8.0/toolchain/segger_embedded_studio/bin/rm C:/Users/shsingha/WorkSpace/SES/Dongle_Test_3/Output/Release/Obj/Dongle_Test_3/ses_startup_nrf52840_PP.s

-include Output/Release/Obj/Dongle_Test_3/thumb_crt0.d
Output/Release/Obj/Dongle_Test_3/thumb_crt0.o:C:/Users/shsingha/ncs/v1.8.0/toolchain/segger_embedded_studio/source/thumb_crt0.s
	C:/Users/shsingha/ncs/v1.8.0/toolchain/segger_embedded_studio/gcc/arm-none-eabi/bin/cc1 -fmessage-length=0 -fno-diagnostics-show-caret -std=gnu99 -E -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -nostdinc -isystemC:/Users/shsingha/ncs/v1.8.0/toolchain/segger_embedded_studio/include -IC:/Users/shsingha/WorkSpace/SES/Dongle_Test_3/nRF/Device/Include "-IC:/Users/shsingha/Nordic/SEGGER Embedded Studio/v3/packages/CMSIS_5/CMSIS/Core/Include" -D__SIZEOF_WCHAR_T=4 -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=8192 -D__SES_VERSION=56800 -D__GNU_LINKER -DNDEBUG -DARM_MATH_CM4 -DNRF52840_XXAA -D__nRF_FAMILY -DFLASH_PLACEMENT=1 -MD C:/Users/shsingha/WorkSpace/SES/Dongle_Test_3/Output/Release/Obj/Dongle_Test_3/thumb_crt0.d -MQ Output/Release/Obj/Dongle_Test_3/thumb_crt0.o -quiet -lang-asm C:/Users/shsingha/ncs/v1.8.0/toolchain/segger_embedded_studio/source/thumb_crt0.s -o C:/Users/shsingha/WorkSpace/SES/Dongle_Test_3/Output/Release/Obj/Dongle_Test_3/thumb_crt0_PP.s
	C:/Users/shsingha/ncs/v1.8.0/toolchain/segger_embedded_studio/gcc/arm-none-eabi/bin/as --traditional-format -IC:/Users/shsingha/WorkSpace/SES/Dongle_Test_3/nRF/Device/Include -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb C:/Users/shsingha/WorkSpace/SES/Dongle_Test_3/Output/Release/Obj/Dongle_Test_3/thumb_crt0_PP.s -o Output/Release/Obj/Dongle_Test_3/thumb_crt0.o -g -gdwarf-4
	C:/Users/shsingha/ncs/v1.8.0/toolchain/segger_embedded_studio/bin/rm C:/Users/shsingha/WorkSpace/SES/Dongle_Test_3/Output/Release/Obj/Dongle_Test_3/thumb_crt0_PP.s

-include Output/Release/Obj/Dongle_Test_3/boards.d
Output/Release/Obj/Dongle_Test_3/boards.o:Driver\ Files/boards.c
	C:/Users/shsingha/ncs/v1.8.0/toolchain/segger_embedded_studio/gcc/arm-none-eabi/bin/cc1 -fmessage-length=0 -fno-diagnostics-show-caret -std=gnu99 -mcpu=cortex-m4 -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -mtp=soft -mfp16-format=ieee -munaligned-access -nostdinc -isystemC:/Users/shsingha/ncs/v1.8.0/toolchain/segger_embedded_studio/include -IC:/Users/shsingha/WorkSpace/SES/Dongle_Test_3/nRF/Device/Include "-IC:/Users/shsingha/Nordic/SEGGER Embedded Studio/v3/packages/CMSIS_5/CMSIS/Core/Include" -D__SIZEOF_WCHAR_T=4 -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=8192 -D__SES_VERSION=56800 -D__GNU_LINKER -DNDEBUG -DARM_MATH_CM4 -DNRF52840_XXAA -D__nRF_FAMILY -DFLASH_PLACEMENT=1 -MD C:/Users/shsingha/WorkSpace/SES/Dongle_Test_3/Output/Release/Obj/Dongle_Test_3/boards.d -MQ Output/Release/Obj/Dongle_Test_3/boards.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -fno-dwarf2-cfi-asm -ffunction-sections -fdata-sections -fshort-enums -fno-common "C:\Users\shsingha\WorkSpace\SES\Dongle_Test_3\Driver Files\boards.c" -o C:/Users/shsingha/WorkSpace/SES/Dongle_Test_3/Output/Release/Obj/Dongle_Test_3/boards.asm
	C:/Users/shsingha/ncs/v1.8.0/toolchain/segger_embedded_studio/gcc/arm-none-eabi/bin/as --traditional-format -IC:/Users/shsingha/WorkSpace/SES/Dongle_Test_3/nRF/Device/Include -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb C:/Users/shsingha/WorkSpace/SES/Dongle_Test_3/Output/Release/Obj/Dongle_Test_3/boards.asm -o Output/Release/Obj/Dongle_Test_3/boards.o
	C:/Users/shsingha/ncs/v1.8.0/toolchain/segger_embedded_studio/bin/rm C:/Users/shsingha/WorkSpace/SES/Dongle_Test_3/Output/Release/Obj/Dongle_Test_3/boards.asm

Output/Release/Exe/Dongle_Test_3.elf:\
  Output/Release/Obj/Dongle_Test_3/system_nrf52.o\
  Output/Release/Obj/Dongle_Test_3/main.o\
  Output/Release/Obj/Dongle_Test_3/ses_startup_nrf_common.o\
  Output/Release/Obj/Dongle_Test_3/ses_startup_nrf52840.o\
  Output/Release/Obj/Dongle_Test_3/thumb_crt0.o\
  Output/Release/Obj/Dongle_Test_3/boards.o\
  flash_placement.xml
	C:/Users/shsingha/ncs/v1.8.0/toolchain/segger_embedded_studio/bin/mkld -memory-map-segments "FLASH RX 0x0 0x100000;RAM1 RWX 0x20000000 0x40000" -section-placement-file C:/Users/shsingha/WorkSpace/SES/Dongle_Test_3/flash_placement.xml -check-segment-overflow -symbols __STACKSIZE__=8192;__STACKSIZE_PROCESS__=0;__HEAPSIZE__=8192 C:/Users/shsingha/WorkSpace/SES/Dongle_Test_3/Output/Release/Obj/Dongle_Test_3/Dongle_Test_3.ld
	C:/Users/shsingha/ncs/v1.8.0/toolchain/segger_embedded_studio/gcc/arm-none-eabi/bin/ld -X --omagic -eReset_Handler --defsym=__do_debug_operation=__do_debug_operation_mempoll -EL --defsym=__vfprintf=__vfprintf_long_nwp --defsym=__vfscanf=__vfscanf_long --gc-sections -TC:/Users/shsingha/WorkSpace/SES/Dongle_Test_3/Output/Release/Obj/Dongle_Test_3/Dongle_Test_3.ld -Map Output/Release/Exe/Dongle_Test_3.map -u_vectors -o Output/Release/Exe/Dongle_Test_3.elf --emit-relocs --start-group @C:/Users/shsingha/WorkSpace/SES/Dongle_Test_3/Output/Release/Obj/Dongle_Test_3/Dongle_Test_3.ind --end-group
	C:/Users/shsingha/ncs/v1.8.0/toolchain/segger_embedded_studio/gcc/arm-none-eabi/bin/objcopy Output/Release/Exe/Dongle_Test_3.elf C:/Users/shsingha/WorkSpace/SES/Dongle_Test_3/Output/Release/Exe/Dongle_Test_3.hex -Oihex